# Generated by Django 4.2.3 on 2023-08-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre del juzgado')),
                ('direccion', models.CharField(max_length=80, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'juzgado',
                'verbose_name_plural': 'juzgados',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='tipo identificacion')),
            ],
            options={
                'verbose_name': 'tipo identificacion',
                'verbose_name_plural': 'tipos identificacion',
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='tipo persona')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10, verbose_name='Numero de identificación')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres completos')),
                ('apelllidos', models.CharField(max_length=80, verbose_name='Apellidos completos')),
                ('fechaNaciemiensto', models.DateField(verbose_name='Fecha naciemiento')),
                ('ciudadResidencia', models.CharField(max_length=80, verbose_name='Ciudad residencia')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('celular', models.CharField(max_length=10, verbose_name='Celular')),
                ('tipoIdentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juzgados.tipodocumento')),
                ('tipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juzgados.tipopersona')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroCaso', models.CharField(max_length=12, verbose_name='numero del caso')),
                ('IdJuzgado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juzgados.juzgado')),
                ('IdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juzgados.persona')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
            },
        ),
    ]
